name: Ejecutar LoginProd.js

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  K6_Execution:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install flask requests

    - name: Instalar k6
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Iniciar Servidor PROD
      run: |
        nohup python prod_app/app.py &

    - name: Esperar a que el servidor PROD esté activo
      run: |
        for i in {1..10}; do
          if curl --silent --fail http://127.0.0.1:5000; then
            echo "Servidor activo!"
            break
          else
            echo "Esperando al servidor..."
            sleep 3
          fi
        done

    - name: Iniciar servidor SHADOW
      run: |
        nohup python sombra_app/appShadow.py &

    - name: Esperar a que el servidor  SHADOW esté activo
      run: |
        for i in {1..10}; do
          if curl --silent --fail http://127.0.0.1:5001; then
            echo "Servidor activo!"
            break
          else
            echo "Esperando al servidor..."
            sleep 3
          fi
        done

    - name: Ejecutar K6 PROD y enviar datos a Grafana Cloud
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      run: |
        echo "Ejecutando test PROD en Grafana Cloud..."
        k6 run --out cloud LoginProd.js

    - name: Ejecutar K6 SHADOW y enviar datos a Grafana Cloud
      env:
        K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      run: |
        echo "Ejecutando test SHADOW en Grafana Cloud..."
        k6 run --out cloud LoginShadow.js




